In [1]:
import numpy as np
import sympy as sp
from scipy import linalg

In [2]:
# ---- DEFINE A MATRIX ----
A = sp.Matrix([
    [2, 1, 0],
    [1, 3, 1],
    [0, 1, 2]
])

print("Matrix A:")
sp.pprint(A)

Matrix A:
⎡2  1  0⎤
⎢       ⎥
⎢1  3  1⎥
⎢       ⎥
⎣0  1  2⎦


In [3]:
# ---- BASIC PROPERTIES ----
print("\nDeterminant:", A.det())
print("Rank:", A.rank())
print("Trace:", A.trace())


Determinant: 8
Rank: 3
Trace: 7


In [8]:
# ---- EIGENVALUES/EIGENVECTORS ----
eigs = A.eigenvects()
print("\nEigenvalues and Eigenvectors:")
for val, mult, vecs in eigs:
    print("\nEigenvalue:", val)
    print("Multiplicity:", mult)
    print("\nEigenvectors:")
    for v in vecs:
        sp.pprint(v)


Eigenvalues and Eigenvectors:

Eigenvalue: 1
Multiplicity: 1

Eigenvectors:
⎡1 ⎤
⎢  ⎥
⎢-1⎥
⎢  ⎥
⎣1 ⎦

Eigenvalue: 2
Multiplicity: 1

Eigenvectors:
⎡-1⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣1 ⎦

Eigenvalue: 4
Multiplicity: 1

Eigenvectors:
⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣1⎦


In [5]:
# ---- NUMERIC VERSION (for large matrices) ----
A_np = np.array(A.tolist(), dtype=float)
w, v = np.linalg.eig(A_np)

print("\nNumPy Eigenvalues:", w)
print("NumPy Eigenvectors:\n", v)


NumPy Eigenvalues: [4. 2. 1.]
NumPy Eigenvectors:
 [[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01 -3.45742585e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]


In [6]:
# ---- NUMERIC VERSION (for large matrices) ----
A_np = np.array(A.tolist(), dtype=float)
w, v = np.linalg.eig(A_np)

print("\nNumPy Eigenvalues:", w)
print("NumPy Eigenvectors:\n", v)


NumPy Eigenvalues: [4. 2. 1.]
NumPy Eigenvectors:
 [[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01 -3.45742585e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]
